import type { EventPlan } from "./event-plan-store.ts";
import {
  createDocument, deleteDocument, FirestoreRestError, getDocument, patchDocument,
  runQuery, SERVER_TIMESTAMP, type FirestoreDocument, type FirestoreRestClient,
} from "./firestore-rest.ts";
import { buildFcmMessage, sendFcmMessage } from "./fcm-client.ts";
import type { PushQueue } from "./handler.ts";
import { parsePushQueueMessage, type DeliveryMessage } from "./queue-messages.ts";
import { getGoogleAccessToken, type GoogleAccessTokenCache } from "./service-account-auth.ts";

export const DEVICE_PAGE_SIZE = 20;
const MAX_DELIVERY_SUBREQUESTS = 39; // Dispatcher reserves the remainder for deferrals.

export interface DeliveryConsumerEnv {
  FIREBASE_PROJECT_ID: string;
  FIREBASE_CLIENT_EMAIL: string;
  FIREBASE_PRIVATE_KEY: string;
  PUSH_DELIVERY_QUEUE: PushQueue<DeliveryMessage>;
}

export interface DeliveryResult {
  externalSubrequests: number;
  devicesProcessed: number;
  completed: boolean;
  stale: boolean;
}

interface DeliveryDependencies {
  createFirestoreClient?: (env: DeliveryConsumerEnv) => Promise<FirestoreRestClient>;
  fetch?: typeof fetch;
  crypto?: Crypto;
  now?: () => number;
}

export class DeliveryProcessingError extends Error {
  constructor() {
    super("Unable to process push delivery");
    this.name = "DeliveryProcessingError";
  }
}

function requireCondition(condition: unknown): asserts condition {
  if (!condition) throw new DeliveryProcessingError();
}

function identifier(value: unknown): value is string {
  return typeof value === "string" && value.length > 0 && value.length <= 256
    && value.trim() === value && !/[\/\u0000-\u001f\u007f]/.test(value)
    && value !== "." && value !== "..";
}

function exactDocument(
  firestore: FirestoreRestClient, path: string, document: FirestoreDocument | null,
): asserts document is FirestoreDocument & { updateTime: string } {
  requireCondition(document && document.name === `projects/${firestore.projectId}/databases/(default)/documents/${path}`
    && typeof document.updateTime === "string");
}

class RequestBudget {
  used = 0;
  readonly maximum: number;
  constructor(maximum: number) { this.maximum = maximum; }
  async run<T>(operation: () => Promise<T>): Promise<T> {
    requireCondition(this.used < this.maximum);
    this.used += 1;
    return operation();
  }
  fetch(fetchImplementation: typeof fetch): typeof fetch {
    return ((input: RequestInfo | URL, init?: RequestInit) => this.run(() => fetchImplementation(input, init))) as typeof fetch;
  }
}

export function createDeliveryConsumer(dependencies: DeliveryDependencies = {}) {
  const cache: GoogleAccessTokenCache = {};
  const now = dependencies.now ?? Date.now;
  return async (
    input: DeliveryMessage, env: DeliveryConsumerEnv, maximumSubrequests = MAX_DELIVERY_SUBREQUESTS,
  ): Promise<DeliveryResult> => {
    // Sanitize every dependency failure, including Queue errors, not only FCM.
    try {
      const message = parsePushQueueMessage(input);
      requireCondition(message.kind === "delivery"
        && Number.isSafeInteger(maximumSubrequests) && maximumSubrequests >= 12 && maximumSubrequests <= MAX_DELIVERY_SUBREQUESTS);
      const budget = new RequestBudget(maximumSubrequests);
      const fetchImplementation = dependencies.fetch ?? globalThis.fetch;
      const base = dependencies.createFirestoreClient ? await dependencies.createFirestoreClient(env) : {
        projectId: env.FIREBASE_PROJECT_ID,
        accessToken: await getGoogleAccessToken(env, cache, now, { fetch: budget.fetch(fetchImplementation), crypto: dependencies.crypto }),
      };
      const firestore = { ...base, fetch: budget.fetch(base.fetch ?? fetchImplementation) };
      const planPath = `pushDeliveryEvents/${message.eventKey}`;
      const recipientPath = `${planPath}/recipients/${message.recipientUid}`;
      const stored = await getDocument(firestore, planPath);
      exactDocument(firestore, planPath, stored);
      requireCondition(stored.fields.schemaVersion === 1 && stored.fields.eventKey === message.eventKey
        && identifier(stored.fields.actorId) && stored.fields.createdAt instanceof Date);
      // Plans are server-generated by event validation, never Queue/client copy.
      const plan = stored.fields as unknown as EventPlan;
      const payload = await buildFcmMessage(plan, message.recipientUid, "inbox-only");
      const recipient = await getDocument(firestore, recipientPath);
      exactDocument(firestore, recipientPath, recipient);
      const state = recipient.fields;
      requireCondition(state.schemaVersion === 1 && state.eventKey === message.eventKey
        && state.recipientUid === message.recipientUid
        && ["pending", "enqueued", "completed"].includes(String(state.status))
        && typeof state.attempts === "number" && Number.isSafeInteger(state.attempts) && state.attempts >= 0
        && (state.deviceCursor == null || identifier(state.deviceCursor)));
      const result = (devicesProcessed: number, completed: boolean, stale = false): DeliveryResult => ({
        externalSubrequests: budget.used, devicesProcessed, completed, stale,
      });
      if (state.status === "completed") return result(0, true);
      const cursor = state.deviceCursor as string | null | undefined ?? null;
      const continuation = (deviceCursor: string | null): DeliveryMessage => ({
        kind: "delivery", eventKey: message.eventKey, recipientUid: message.recipientUid,
        ...(deviceCursor === null ? {} : { deviceCursor }),
      });
      if ((message.deviceCursor ?? null) !== cursor) {
        await budget.run(() => env.PUSH_DELIVERY_QUEUE.send(continuation(cursor)));
        return result(0, false, true);
      }

      const notificationId = payload.data.notificationId;
      const inboxCollection = `users/${message.recipientUid}/pushNotifications`;
      try {
        await createDocument(firestore, inboxCollection, notificationId, {
          id: notificationId, eventKey: plan.eventKey, type: plan.type,
          title: payload.notification.title, body: payload.notification.body,
          data: plan.data, actorId: plan.actorId, createdAt: SERVER_TIMESTAMP, read: false,
        });
      } catch (error) {
        if (!(error instanceof FirestoreRestError) || error.status !== 409) throw error;
        const existing = await getDocument(firestore, `${inboxCollection}/${notificationId}`);
        exactDocument(firestore, `${inboxCollection}/${notificationId}`, existing);
        requireCondition(existing.fields.id === notificationId && existing.fields.eventKey === plan.eventKey
          && existing.fields.type === plan.type && typeof existing.fields.read === "boolean");
        // No patch on the duplicate path: read:true and createdAt are immutable here.
      }

      const deviceCollection = `users/${message.recipientUid}/devices`;
      const devicePrefix = `projects/${firestore.projectId}/databases/(default)/documents/${deviceCollection}/`;
      const page = await runQuery(firestore, `users/${message.recipientUid}`, {
        from: [{ collectionId: "devices" }],
        orderBy: [{ field: { fieldPath: "__name__" }, direction: "ASCENDING" }],
        limit: DEVICE_PAGE_SIZE,
        ...(cursor === null ? {} : { startAt: { values: [{ referenceValue: devicePrefix + cursor }], before: false } }),
      });
      requireCondition(page.length <= DEVICE_PAGE_SIZE);
      let devicesProcessed = 0;
      let nextCursor = cursor;
      for (const device of page) {
        // Reserve two calls for send+possible delete, plus CAS and continuation.
        if (budget.maximum - budget.used < 4) break;
        requireCondition(device.name.startsWith(devicePrefix));
        const deviceId = device.name.slice(devicePrefix.length);
        requireCondition(identifier(deviceId) && device.fields.deviceId === deviceId
          && typeof device.updateTime === "string"
          && (device.fields.platform === "android" || device.fields.platform === "ios")
          && typeof device.fields.token === "string" && device.fields.token.length > 0 && device.fields.token.length <= 4096);
        const outcome = await sendFcmMessage({
          projectId: firestore.projectId, accessToken: firestore.accessToken,
          fetch: budget.fetch(fetchImplementation),
        }, { ...payload, token: device.fields.token });
        requireCondition(outcome !== "retryable");
        if (outcome === "invalid_token") {
          try {
            await deleteDocument(firestore, `${deviceCollection}/${deviceId}`, { precondition: { updateTime: device.updateTime } });
          } catch (error) {
            // A concurrently refreshed token is not the invalid token we sent.
            if (!(error instanceof FirestoreRestError) || ![409, 412].includes(error.status ?? 0)) throw error;
          }
        }
        nextCursor = deviceId;
        devicesProcessed += 1;
      }
      const completed = devicesProcessed === page.length && page.length < DEVICE_PAGE_SIZE;
      await patchDocument(firestore, recipientPath, {
        deviceCursor: nextCursor,
        ...(completed ? { status: "completed", completedAt: SERVER_TIMESTAMP } : {}),
      }, {
        updateMask: completed ? ["deviceCursor", "status", "completedAt"] : ["deviceCursor"],
        precondition: { updateTime: recipient.updateTime },
      });
      if (!completed) {
        await budget.run(() => env.PUSH_DELIVERY_QUEUE.send(continuation(nextCursor)));
      }
      return result(devicesProcessed, completed);
    } catch {
      throw new DeliveryProcessingError();
    }
  };
}

export const handleDeliveryMessage = createDeliveryConsumer();
